export const COPY = {
  app: {
    name: "Situ",
    tagline: "Caregiver shift monitoring",
  },
  home: {
    title: "Choose a perspective",
    subtitle: "Explore the shift monitoring flow from each actor's point of view.",
    caregiver: {
      title: "Caregiver",
      description: "See today's shift, start the trip and check in.",
    },
    operations: {
      title: "Operations",
      description: "Monitor active shifts, detect delays and assign replacements.",
    },
    family: {
      title: "Family",
      description: "Follow the caregiver's arrival and decide how to respond.",
    },
    reset: "Reset demo state",
    resetToast: "Demo state reset.",
  },
  caregiver: {
    title: "Today's shift",
    shiftsTitle: "Your shifts",
    shiftsSubtitle: "Your upcoming and past shifts. Today's shift is highlighted.",
    activeBadge: "Today",
    tabUpcoming: "Active & upcoming",
    tabCompleted: "Completed",
    noShifts: "No shifts here.",
    olderAdult: "Older adult",
    family: "Family",
    address: "Address",
    startTime: "Start time",
    status: "Status",
    startTrip: "Start trip",
    tripStartedToast: "Trip started. Location sharing is now active.",
    states: {
      start: "Ready to start",
      onTheWay: "On the way",
      delayed: "Running late",
      inProgress: "Shift in progress",
      replacementRequested: "Replacement in progress",
      replacementAssigned: "Replacement confirmed",
      cancelled: "Cancelled due to delay",
      done: "Completed",
    },
  },
  shiftDetail: {
    title: "Shift detail",
    infoOnly: "This shift hasn't started. You can review its details here.",
    startTrip: "Start trip",
    goToTrip: "Go to trip",
    checkIn: "Check in",
    medicalRecord: "Medical record",
    viewPrevious: "View previous records",
    hidePrevious: "Hide previous records",
    fillCurrent: "Fill current record",
    currentRecord: "Current record",
    notCheckedInToast: "You haven't marked your arrival yet. Check in first to fill the record.",
    noPrevious: "No previous records for this older adult.",
    recordedByCaregiver: "Filled by the caregiver",
    recordedByFamily: "Filled by the family",
    cancelledNote: "This shift was cancelled due to a delay. A replacement caregiver was assigned.",
  },
  tracking: {
    title: "Trip in progress",
    eta: "Estimated arrival",
    distance: "Distance",
    status: "Status",
    /** Map note explaining the simulated update cadence; interval comes from constants. */
    updateNote: (intervalMinutes: number): string =>
      `Your location should be shared every ${intervalMinutes} minutes.`,
    shareLocation: "Share my location",
    locationDialog: {
      title: "Location update (demo control)",
      description:
        "This dialog is for the demo presenter, not part of the prototype. Choose what the next location update should report.",
      onTime: "Arriving on time",
      runningLate: "Running late",
    },
    onTimeToast: "Location shared. You're on track to arrive on time.",
    reportLate: "I'm running late",
    reportLateToast: "Thanks for letting us know. We've updated your ETA and notified Situ.",
    checkIn: "Check in",
    familyWaiting: "The family has decided to wait for you. If you're delayed further, we'll check with them again.",
  },
  delay: {
    title: "Delay detected",
    warning: "You're running late for this shift.",
    operationsNotified: "Operations has been notified.",
    familyNotified: "The family has been notified.",
    newEta: "Updated arrival",
    continue: "Continue",
  },
  simulate: {
    delay: "Simulate delay",
    toast: "Delay simulated. ETA updated for the active shift.",
    ariaLabel: "Demo control: simulate a delay on the active shift",
  },
  operations: {
    title: "Operations",
    subtitle: "Monitor today's shifts and manage incidents.",
    tabActive: "Active",
    tabUpcoming: "Upcoming",
    tabCalendar: "Calendar",
    noActive: "No active shifts right now.",
    noUpcoming: "No upcoming shifts.",
    noCalendar: "No shifts scheduled.",
    stateLabel: {
      ok: "On track",
      pending: "Awaiting info",
      late: "Running late",
    },
    familyDecision: {
      waiting: "Family waiting",
      requested: "Replacement requested",
    },
    activeShift: "Active shift",
    assignedCaregiver: "Assigned caregiver",
    eta: "ETA",
    risk: "Risk level",
    verifications: "Verification checks",
    suggestions: "Replacement suggestions",
    suggestionsDisabledNote:
      "Replacement options become available when the caregiver reports a delay.",
    pendingNote: "The caregiver hasn't confirmed departure or arrival yet.",
    contactFamily: "Contact family",
    contactToast: "Family contacted about the delay.",
    sendReminder: "Send location reminder",
    reminderToast: "Reminder sent. The caregiver was asked to share their location.",
    manageReplacement: "Manage replacement",
    assignReplacement: "Assign replacement",
    assignedToast: "Replacement assigned successfully.",
    empty: "No replacement candidates available right now.",
    assignedBanner: "Replacement assigned. The original shift was cancelled due to the delay.",
    checklist: {
      departureConfirmed: "Departure confirmed",
      locationShared: "Location shared",
      arrivalConfirmed: "Arrival confirmed",
      received: "Received",
      pending: "Pending",
    },
  },
  operationsReplacement: {
    title: "Assign a replacement",
    subtitle: (familyName: string): string => `Covering ${familyName}'s shift`,
    shiftWindow: (start: string, end: string): string => `Shift ${start}–${end}`,
    available: (from: string, until: string): string => `Available ${from}–${until}`,
    assignFull: "Assign full-shift replacement",
    assignMomentary: "Assign momentary replacement",
    fullDisabledNote: "Can't cover the full shift with this caregiver's availability.",
    covers: (until: string, hours: number): string => `Covers until ${until} · ${hours} h`,
    remaining: (from: string, until: string): string => `Still to cover: ${from}–${until}`,
    fullyCovered: "Covers the full shift.",
    assignedCaregiver: "Assigned caregiver",
    originalCaregiver: "Original caregiver",
    fullyReplaced: "Fully replaced",
    changeSchedule: "Change schedule",
    reassignedNote: (from: string, until: string): string =>
      `Reassigned to cover ${from}–${until}`,
    newShiftBadge: "New shift",
    assignedToastFull: "Full-shift replacement assigned.",
    assignedToastMomentary: "Momentary replacement assigned.",
    reassignToast: "Original caregiver reassigned to the remaining hours.",
    noCandidates: "No replacement candidates available.",
    backToProfile: "Back to shift",
    proposeRotation: "Propose caregiver rotation",
    proposeRotationNote:
      "No free backup covers the full shift? Offer a swap with a caregiver assigned to another family.",
    rotationInProgress: "A caregiver rotation is in progress for this shift.",
    viewRotation: "View rotation",
    rejectedCandidateNote: "Declined a previous rotation.",
  },
  operationsSwap: {
    title: "Rotate caregivers",
    subtitle: (familyName: string): string => `Find a swap to cover ${familyName}'s shift`,
    pickTitle: "Caregivers from other families",
    pickHelp:
      "Propose a swap with a caregiver currently assigned to another family. The delayed caregiver would cover that other shift instead. All four parties must accept.",
    noCandidates:
      "No compatible caregiver from another family right now. Go back and assign a free backup, or let the family wait.",
    viableNew: (eta: string): string => `Arrives in ${eta} — sooner than the delayed caregiver.`,
    viableOriginal: (start: string, end: string): string =>
      `Delayed caregiver can cover ${start}–${end} afterwards.`,
    currentShift: (start: string, end: string): string => `Current shift ${start}–${end}`,
    propose: "Propose swap",
    proposeToast: "Swap proposed. All four parties were notified.",
    summaryTitle: "Caregiver rotation in progress",
    summaryHint: "View coordination",
    coordinationTitle: "Swap coordination",
    coordinationHelp:
      "Each party answers from their own view. The operator only tracks the request and applies it once all four accept. A single decline cancels the swap.",
    donorAssumed:
      "For this demo, the other family and the other caregiver are assumed to have accepted. Waiting on the affected family and the delayed caregiver.",
    progress: (accepted: number): string => `${accepted}/4 parties accepted`,
    roleLabel: {
      caregiverA: "Delayed caregiver",
      caregiverB: "New caregiver",
      familyA: "Affected family",
      familyB: "Other family",
    },
    roleMove: {
      caregiverA: (familyName: string): string => `Would move to ${familyName}`,
      caregiverB: (familyName: string): string => `Would move to ${familyName}`,
      familyA: (caregiverName: string): string => `Would receive ${caregiverName}`,
      familyB: (caregiverName: string): string => `Would receive ${caregiverName}`,
    },
    apply: "Apply swap",
    applyNote: "Enabled once all four parties accept.",
    applyToast: "Swap applied. Both caregivers were reassigned.",
    cancelledNote:
      "The swap was cancelled because a party declined. The caregiver drops to the bottom of the list and the family is asked to wait or look for another replacement.",
    appliedNote: (caregiverB: string, familyA: string, caregiverA: string, familyB: string): string =>
      `${caregiverB} now covers ${familyA}; ${caregiverA} now covers ${familyB}.`,
    backToReplacement: "Back to replacement",
    notLate:
      "A rotation can only be proposed for a delayed shift.",
  },
  swap: {
    title: "Caregiver rotation",
    familyAPrompt: (caregiverName: string): string =>
      `Operations proposes ${caregiverName} to cover today's shift instead of your delayed caregiver. Do you accept the change?`,
    familyBPrompt: (caregiverName: string): string =>
      `Operations asks to send your caregiver to another family and have ${caregiverName} cover your shift. Do you accept?`,
    caregiverAPrompt: (familyName: string): string =>
      `A replacement was requested for your delayed shift. Are you available to take a shift with ${familyName} instead?`,
    caregiverBPrompt: (familyName: string): string =>
      `Operations asks if you can cover a shift with ${familyName} instead of your current one.`,
    newCaregiver: "New caregiver",
    shiftInfo: "Shift details",
    startsAt: (time: string): string => `Starts at ${time}`,
    travel: (eta: string, distance: string): string => `${eta} away · ${distance}`,
    reliability: (pct: string): string => `${pct} reliability`,
    accept: "Accept rotation",
    decline: "Decline rotation",
    acceptToast: "Response recorded: accepted.",
    declineToast: "Response recorded: declined.",
    acceptedWaiting: "You accepted. Waiting for the other parties to respond.",
    declinedByYou: "You declined this rotation.",
    cancelledMessage: "This rotation was cancelled because one of the parties declined.",
    appliedMessage: "The rotation was confirmed. Schedules have been updated.",
  },
  family: {
    title: "Your caregiver",
    dashboardTitle: "Your shifts",
    dashboardSubtitle: "Your upcoming shifts and who will attend.",
    viewRecords: "View record history",
    withCaregiver: (name: string): string => `With ${name}`,
    infoOnly: "This shift hasn't started yet. You can review its details here.",
    currentCaregiver: "Current caregiver",
    arrival: "Estimated arrival",
    delayMessage: "Your caregiver is delayed. We are monitoring the situation.",
    onTimeMessage: "Your caregiver is on the way and on time.",
    wait: "Wait",
    requestReplacement: "Request replacement",
    waitToast: "Thanks. We'll keep you updated.",
    requestToast: "Replacement requested. Operations is finding a match.",
    replacementRequestedNote:
      "Replacement requested. We've notified operations — you'll be updated as soon as a caregiver is assigned.",
    rotationInProgressMessage:
      "A caregiver rotation is in progress. We're waiting for everyone to confirm the change.",
    fillRecord: "Fill medical record",
    fillRecordNote: "The caregiver is running late. You can fill in the medical record now.",
    reportNotArrived: "Report caregiver not arrived",
    reportNote: "The shift is about to start and the caregiver hasn't checked in yet.",
    reportToast: "Reported. Operations has been notified.",
    replacementAssigned: "A replacement caregiver has been assigned and is on the way.",
    records: {
      title: "Medical record history",
      subtitle: "Records filled for your family member.",
      empty: "No records have been filled yet.",
    },
  },
  replacement: {
    /** Human-readable match summary, composed from already-formatted values. */
    matchNote: (etaLabel: string, distanceLabel: string, reliabilityLabel: string): string =>
      `Arrives in ${etaLabel}, ${distanceLabel} away, ${reliabilityLabel} reliability.`,
  },
  checkIn: {
    title: "Check in",
    arrivalTime: "Arrival time",
    addressConfirm: "Confirm you are at the address below",
    checkIn: "Check in",
    toast: "Checked in. Shift has started.",
  },
  handoff: {
    title: "Shift handoff",
    subtitle: "Summarize how the shift went before you leave.",
    familySubtitle: "Fill in the medical record while you wait for the caregiver.",
    sleepQuality: "Quality of sleep",
    mood: "Mood",
    medicationChanges: "Medication changes",
    recentEvents: "Recent events",
    notes: "Notes",
    finish: "Finish",
    toast: "Handoff submitted. Shift completed.",
    familyToast: "Medical record saved. Thank you.",
  },
  common: {
    back: "Back",
    backToHome: "Back to home",
    close: "Close",
    minutesShort: "min",
    kmShort: "km",
    timePlaceholder: "--:--",
    dismissNotification: "Dismiss notification",
  },
} as const;
