export const COPY = {
  app: {
    name: "Situ",
    tagline: "Caregiver shift monitoring",
  },
  home: {
    title: "Choose a perspective",
    subtitle: "Explore the shift monitoring flow from each actor's point of view.",
    caregiver: {
      title: "Caregiver",
      description: "See today's shift, start the trip and check in.",
    },
    operations: {
      title: "Operations",
      description: "Monitor active shifts, detect delays and assign replacements.",
    },
    family: {
      title: "Family",
      description: "Follow the caregiver's arrival and decide how to respond.",
    },
  },
  caregiver: {
    title: "Today's shift",
    olderAdult: "Older adult",
    family: "Family",
    address: "Address",
    startTime: "Start time",
    status: "Status",
    startTrip: "Start trip",
    tripStartedToast: "Trip started. Location sharing is now active.",
  },
  tracking: {
    title: "Trip in progress",
    eta: "Estimated arrival",
    distance: "Distance",
    status: "Status",
    updateNote: "Location updates automatically every 15 minutes.",
    simulateDelay: "Simulate delay",
    checkIn: "Check in",
    delayToast: "Delay detected. Operations and family have been notified.",
  },
  delay: {
    title: "Delay detected",
    warning: "The caregiver is running late for this shift.",
    operationsNotified: "Operations has been notified.",
    familyNotified: "The family has been notified.",
    newEta: "Updated arrival",
    continue: "Continue",
  },
  operations: {
    title: "Operations dashboard",
    activeShift: "Active shift",
    eta: "ETA",
    risk: "Risk level",
    suggestions: "Replacement suggestions",
    contactFamily: "Contact family",
    assignReplacement: "Assign replacement",
    contactToast: "Family contacted about the delay.",
    assignedToast: "Replacement assigned successfully.",
    empty: "No replacement candidates available right now.",
  },
  family: {
    title: "Your caregiver",
    currentCaregiver: "Current caregiver",
    arrival: "Estimated arrival",
    delayMessage: "Your caregiver is delayed. We are monitoring the situation.",
    onTimeMessage: "Your caregiver is on the way and on time.",
    wait: "Wait",
    requestReplacement: "Request replacement",
    waitToast: "Thanks. We'll keep you updated.",
    requestToast: "Replacement requested. Operations is finding a match.",
  },
  replacement: {
    title: "Replacement match",
    suggested: "Suggested caregiver",
    distance: "Distance",
    eta: "ETA",
    matchNotes: "Match notes",
    accept: "Accept replacement",
    reject: "Reject replacement",
    acceptToast: "Replacement accepted. The new caregiver is on the way.",
    rejectToast: "Replacement rejected. Looking for another match.",
    /** Human-readable match summary, composed from already-formatted values. */
    matchNote: (etaLabel: string, distanceLabel: string, reliabilityLabel: string): string =>
      `Arrives in ${etaLabel}, ${distanceLabel} away, ${reliabilityLabel} reliability.`,
  },
  checkIn: {
    title: "Check in",
    arrivalTime: "Arrival time",
    addressConfirm: "Confirm you are at the address below",
    checkIn: "Check in",
    toast: "Checked in. Shift has started.",
  },
  handoff: {
    title: "Shift handoff",
    subtitle: "Summarize how the shift went before you leave.",
    sleepQuality: "Quality of sleep",
    mood: "Mood",
    medicationChanges: "Medication changes",
    recentEvents: "Recent events",
    notes: "Notes",
    finish: "Finish",
    toast: "Handoff submitted. Shift completed.",
  },
  common: {
    back: "Back",
    backToHome: "Back to home",
    minutesShort: "min",
    kmShort: "km",
    timePlaceholder: "--:--",
    dismissNotification: "Dismiss notification",
  },
} as const;
