export const COPY = {
  app: {
    name: "Situ",
    tagline: "Monitoreo de turnos de cuidado",
  },
  home: {
    title: "Elige una perspectiva",
    subtitle: "Explora el flujo de monitoreo del turno desde el punto de vista de cada actor.",
    caregiver: {
      title: "Cuidadora",
      description: "Revisa el turno de hoy, inicia el traslado y registra la llegada.",
    },
    operations: {
      title: "Operaciones (Situ)",
      description: "Monitorea turnos activos, detecta atrasos y asigna reemplazos.",
    },
    family: {
      title: "Familia",
      description: "Sigue la llegada de la cuidadora y decide cómo responder.",
    },
    reset: "Reiniciar demo",
    resetToast: "Estado de demo reiniciado.",
  },
  status: {
    scheduled: "Programado",
    trip_started: "Traslado iniciado",
    delay_detected: "Atraso detectado",
    replacement_requested: "Reemplazo solicitado",
    replacement_assigned: "Reemplazo asignado",
    cancelled: "Cancelado por atraso",
    arrived: "Llegada registrada",
    shift_started: "Turno iniciado",
    completed: "Completado",
  },
  risk: {
    low: "Riesgo bajo",
    medium: "Riesgo medio",
    high: "Riesgo alto",
  },
  swapDecision: {
    accepted: "Aceptado",
    pending: "Esperando respuesta",
    rejected: "Rechazado",
  },
  swapStatus: {
    proposed: "Esperando respuestas",
    accepted: "Todas las partes aceptaron",
    rejected: "Rotación cancelada",
    applied: "Rotación aplicada",
  },
  caregiver: {
    title: "Turno de hoy",
    shiftsTitle: "Tus turnos",
    shiftsSubtitle: "Tus turnos próximos y anteriores. El turno de hoy está destacado.",
    activeBadge: "Hoy",
    tabUpcoming: "Activos y próximos",
    tabCompleted: "Completados",
    noShifts: "No hay turnos aquí.",
    olderAdult: "Adulto mayor",
    family: "Familia",
    address: "Dirección",
    startTime: "Hora de inicio",
    status: "Estado",
    startTrip: "Iniciar traslado",
    tripStartedToast: "Traslado iniciado. Ahora se comparte la ubicación.",
    states: {
      start: "Lista para iniciar",
      onTheWay: "En camino",
      delayed: "Con atraso",
      inProgress: "Turno en curso",
      replacementRequested: "Reemplazo en gestión",
      replacementAssigned: "Reemplazo confirmado",
      cancelled: "Cancelado por atraso",
      done: "Completado",
    },
  },
  shiftDetail: {
    title: "Detalle del turno",
    infoOnly: "Este turno aún no comienza. Puedes revisar sus detalles aquí.",
    startTrip: "Iniciar traslado",
    goToTrip: "Ir al traslado",
    checkIn: "Registrar llegada",
    medicalRecord: "Ficha de cuidado",
    viewPrevious: "Ver fichas anteriores",
    hidePrevious: "Ocultar fichas anteriores",
    fillCurrent: "Completar ficha actual",
    currentRecord: "Ficha actual",
    notCheckedInToast: "Aún no registras tu llegada. Haz check-in antes de completar la ficha.",
    noPrevious: "No hay fichas anteriores para este adulto mayor.",
    recordedByCaregiver: "Completada por la cuidadora",
    recordedByFamily: "Completada por la familia",
    cancelledNote: "Este turno fue cancelado por atraso. Se asignó una cuidadora de reemplazo.",
  },
  tracking: {
    title: "Traslado en curso",
    eta: "Llegada estimada",
    distance: "Distancia",
    status: "Estado",
    /** Map note explaining the simulated update cadence; interval comes from constants. */
    updateNote: (intervalMinutes: number): string =>
      `Tu ubicación debería compartirse cada ${intervalMinutes} minutos.`,
    shareLocation: "Compartir mi ubicación",
    locationDialog: {
      title: "Actualización de ubicación (control de demo)",
      description:
        "Este diálogo es para quien presenta la demo, no forma parte del prototipo. Elige qué debe reportar la próxima actualización de ubicación.",
      onTime: "Llegada a tiempo",
      runningLate: "Con atraso",
    },
    onTimeToast: "Ubicación compartida. Vas a tiempo para llegar.",
    reportLate: "Voy atrasada",
    reportLateToast: "Gracias por avisar. Actualizamos tu ETA y notificamos a Situ.",
    checkIn: "Registrar llegada",
    familyWaiting:
      "La familia decidió esperarte. Si el atraso aumenta, volveremos a consultarles.",
  },
  delay: {
    title: "Atraso detectado",
    warning: "Estás atrasada para este turno.",
    operationsNotified: "Operaciones fue notificado.",
    familyNotified: "La familia fue notificada.",
    newEta: "Llegada actualizada",
    continue: "Continuar",
  },
  simulate: {
    delay: "Simular atraso",
    toast: "Atraso simulado. El ETA del turno activo fue actualizado.",
    ariaLabel: "Control de demo: simular atraso en el turno activo",
  },
  operations: {
    title: "Operaciones",
    subtitle: "Monitorea los turnos de hoy y gestiona incidentes.",
    tabActive: "Activos",
    tabUpcoming: "Próximos",
    tabCalendar: "Calendario",
    noActive: "No hay turnos activos en este momento.",
    noUpcoming: "No hay turnos próximos.",
    noCalendar: "No hay turnos programados.",
    stateLabel: {
      ok: "En ruta",
      pending: "Esperando información",
      late: "Con atraso",
    },
    familyDecision: {
      waiting: "Familia espera",
      requested: "Reemplazo solicitado",
    },
    activeShift: "Turno activo",
    assignedCaregiver: "Cuidadora asignada",
    eta: "ETA",
    risk: "Nivel de riesgo",
    verifications: "Checklist de verificación",
    suggestions: "Sugerencias de reemplazo",
    suggestionsDisabledNote:
      "Las opciones de reemplazo se habilitan cuando la cuidadora reporta un atraso.",
    pendingNote: "La cuidadora aún no confirma salida ni llegada.",
    contactFamily: "Contactar familia",
    contactToast: "Familia contactada por el atraso.",
    sendReminder: "Enviar recordatorio de ubicación",
    reminderToast: "Recordatorio enviado. Se pidió a la cuidadora compartir su ubicación.",
    manageReplacement: "Gestionar reemplazo",
    assignReplacement: "Asignar reemplazo",
    assignedToast: "Reemplazo asignado correctamente.",
    empty: "No hay candidatas de reemplazo disponibles en este momento.",
    assignedBanner: "Reemplazo asignado. El turno original fue cancelado por el atraso.",
    checklist: {
      departureConfirmed: "Salida confirmada",
      locationShared: "Ubicación compartida",
      arrivalConfirmed: "Llegada confirmada",
      received: "Recibido",
      pending: "Pendiente",
    },
  },
  operationsReplacement: {
    title: "Asignar reemplazo",
    subtitle: (familyName: string): string => `Cubriendo el turno de ${familyName}`,
    shiftWindow: (start: string, end: string): string => `Turno ${start}-${end}`,
    available: (from: string, until: string): string => `Disponible ${from}-${until}`,
    assignFull: "Asignar reemplazo de turno completo",
    assignMomentary: "Asignar reemplazo momentáneo",
    fullDisabledNote: "Esta cuidadora no cubre el turno completo con su disponibilidad.",
    covers: (until: string, hours: number): string => `Cubre hasta ${until} · ${hours} h`,
    remaining: (from: string, until: string): string => `Aún por cubrir: ${from}-${until}`,
    fullyCovered: "Cubre el turno completo.",
    assignedCaregiver: "Cuidadora asignada",
    originalCaregiver: "Cuidadora original",
    fullyReplaced: "Reemplazo completo",
    changeSchedule: "Cambiar horario",
    reassignedNote: (from: string, until: string): string =>
      `Reasignada para cubrir ${from}-${until}`,
    newShiftBadge: "Nuevo turno",
    assignedToastFull: "Reemplazo de turno completo asignado.",
    assignedToastMomentary: "Reemplazo momentáneo asignado.",
    reassignToast: "Cuidadora original reasignada a las horas restantes.",
    noCandidates: "No hay candidatas de reemplazo disponibles.",
    backToProfile: "Volver al turno",
    proposeRotation: "Proponer rotación de cuidadoras",
    proposeRotationNote:
      "Ningún respaldo libre cubre el turno completo. Ofrece un intercambio con una cuidadora asignada a otra familia.",
    rotationInProgress: "Hay una rotación de cuidadoras en curso para este turno.",
    viewRotation: "Ver rotación",
    rejectedCandidateNote: "Rechazó una rotación anterior.",
  },
  operationsSwap: {
    title: "Rotar cuidadoras",
    subtitle: (familyName: string): string => `Busca un intercambio para cubrir el turno de ${familyName}`,
    pickTitle: "Cuidadoras de otras familias",
    pickHelp:
      "Propone un intercambio con una cuidadora actualmente asignada a otra familia. La cuidadora atrasada cubriría ese otro turno. Las cuatro partes deben aceptar.",
    noCandidates:
      "No hay una cuidadora compatible de otra familia en este momento. Vuelve y asigna un respaldo libre, o deja que la familia espere.",
    viableNew: (eta: string): string => `Llega en ${eta}; antes que la cuidadora atrasada.`,
    viableOriginal: (start: string, end: string): string =>
      `La cuidadora atrasada puede cubrir ${start}-${end} después.`,
    currentShift: (start: string, end: string): string => `Turno actual ${start}-${end}`,
    propose: "Proponer intercambio",
    proposeToast: "Intercambio propuesto. Las cuatro partes fueron notificadas.",
    summaryTitle: "Rotación de cuidadoras en curso",
    summaryHint: "Ver coordinación",
    coordinationTitle: "Coordinación del intercambio",
    coordinationHelp:
      "Cada parte responde desde su propia vista. Operaciones solo da seguimiento a la solicitud y la aplica cuando las cuatro partes aceptan. Un rechazo cancela el intercambio.",
    donorAssumed:
      "Para esta demo, la otra familia y la otra cuidadora se consideran aceptadas. Falta la respuesta de la familia afectada y de la cuidadora atrasada.",
    progress: (accepted: number): string => `${accepted}/4 partes aceptaron`,
    roleLabel: {
      caregiverA: "Cuidadora atrasada",
      caregiverB: "Nueva cuidadora",
      familyA: "Familia afectada",
      familyB: "Otra familia",
    },
    roleMove: {
      caregiverA: (familyName: string): string => `Pasaría a ${familyName}`,
      caregiverB: (familyName: string): string => `Pasaría a ${familyName}`,
      familyA: (caregiverName: string): string => `Recibiría a ${caregiverName}`,
      familyB: (caregiverName: string): string => `Recibiría a ${caregiverName}`,
    },
    apply: "Aplicar intercambio",
    applyNote: "Se habilita cuando las cuatro partes aceptan.",
    applyToast: "Intercambio aplicado. Ambas cuidadoras fueron reasignadas.",
    cancelledNote:
      "El intercambio se canceló porque una parte rechazó. La cuidadora baja al final de la lista y se pide a la familia esperar o buscar otro reemplazo.",
    appliedNote: (caregiverB: string, familyA: string, caregiverA: string, familyB: string): string =>
      `${caregiverB} ahora cubre a ${familyA}; ${caregiverA} ahora cubre a ${familyB}.`,
    backToReplacement: "Volver a reemplazo",
    notLate: "Solo se puede proponer una rotación para un turno atrasado.",
  },
  swap: {
    title: "Rotación de cuidadoras",
    familyAPrompt: (caregiverName: string): string =>
      `Operaciones propone que ${caregiverName} cubra el turno de hoy en lugar de tu cuidadora atrasada. ¿Aceptas el cambio?`,
    familyBPrompt: (caregiverName: string): string =>
      `Operaciones solicita enviar a tu cuidadora a otra familia y que ${caregiverName} cubra tu turno. ¿Aceptas?`,
    caregiverAPrompt: (familyName: string): string =>
      `Se solicitó un reemplazo para tu turno atrasado. ¿Estás disponible para tomar un turno con ${familyName} en su lugar?`,
    caregiverBPrompt: (familyName: string): string =>
      `Operaciones pregunta si puedes cubrir un turno con ${familyName} en lugar del actual.`,
    newCaregiver: "Nueva cuidadora",
    shiftInfo: "Detalles del turno",
    startsAt: (time: string): string => `Comienza a las ${time}`,
    travel: (eta: string, distance: string): string => `${eta} de traslado · ${distance}`,
    reliability: (pct: string): string => `${pct} de confiabilidad`,
    accept: "Aceptar rotación",
    decline: "Rechazar rotación",
    acceptToast: "Respuesta registrada: aceptada.",
    declineToast: "Respuesta registrada: rechazada.",
    acceptedWaiting: "Aceptaste. Esperando que respondan las otras partes.",
    declinedByYou: "Rechazaste esta rotación.",
    cancelledMessage: "Esta rotación fue cancelada porque una de las partes rechazó.",
    appliedMessage: "La rotación fue confirmada. Los horarios fueron actualizados.",
  },
  family: {
    title: "Tu cuidadora",
    dashboardTitle: "Tus turnos",
    dashboardSubtitle: "Tus próximos turnos y quién asistirá.",
    viewRecords: "Ver historial de fichas",
    withCaregiver: (name: string): string => `Con ${name}`,
    infoOnly: "Este turno aún no comienza. Puedes revisar sus detalles aquí.",
    currentCaregiver: "Cuidadora actual",
    arrival: "Llegada estimada",
    delayMessage: "Tu cuidadora está atrasada. Estamos monitoreando la situación.",
    onTimeMessage: "Tu cuidadora está en camino y a tiempo.",
    wait: "Esperar",
    requestReplacement: "Solicitar reemplazo",
    waitToast: "Gracias. Te mantendremos al tanto.",
    requestToast: "Reemplazo solicitado. Operaciones está buscando una candidata.",
    replacementRequestedNote:
      "Reemplazo solicitado. Notificamos a operaciones; te avisaremos apenas se asigne una cuidadora.",
    rotationInProgressMessage:
      "Hay una rotación de cuidadoras en curso. Estamos esperando que todas las partes confirmen el cambio.",
    fillRecord: "Completar ficha de cuidado",
    fillRecordNote: "La cuidadora está atrasada. Puedes completar la ficha de cuidado ahora.",
    reportNotArrived: "Reportar que la cuidadora no llegó",
    reportNote: "El turno está por comenzar y la cuidadora aún no registra llegada.",
    reportToast: "Reporte enviado. Operaciones fue notificado.",
    replacementAssigned: "Se asignó una cuidadora de reemplazo y ya va en camino.",
    records: {
      title: "Historial de fichas de cuidado",
      subtitle: "Fichas completadas para tu familiar.",
      empty: "Aún no hay fichas completadas.",
    },
  },
  replacement: {
    /** Human-readable match summary, composed from already-formatted values. */
    matchNote: (etaLabel: string, distanceLabel: string, reliabilityLabel: string): string =>
      `Llega en ${etaLabel}, a ${distanceLabel}, con ${reliabilityLabel} de confiabilidad.`,
  },
  checkIn: {
    title: "Registrar llegada",
    arrivalTime: "Hora de llegada",
    addressConfirm: "Confirma que estás en la dirección indicada",
    checkIn: "Registrar llegada",
    toast: "Llegada registrada. El turno comenzó.",
  },
  handoff: {
    title: "Ficha de cierre",
    subtitle: "Resume cómo estuvo el turno antes de retirarte.",
    familySubtitle: "Completa la ficha de cuidado mientras esperas a la cuidadora.",
    sleepQuality: "Calidad del sueño",
    mood: "Estado de ánimo",
    medicationChanges: "Cambios de medicamentos",
    recentEvents: "Eventos recientes",
    notes: "Notas",
    finish: "Finalizar",
    toast: "Ficha enviada. Turno completado.",
    familyToast: "Ficha de cuidado guardada. Gracias.",
  },
  common: {
    back: "Volver",
    backToHome: "Volver al inicio",
    close: "Cerrar",
    minutesShort: "min",
    kmShort: "km",
    timePlaceholder: "--:--",
    dismissNotification: "Descartar notificación",
  },
} as const;
